# Generated by Django 4.0.10 on 2024-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_number', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('pay_acc_numb', models.AutoField(primary_key=True, serialize=False)),
                ('number_card', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_code', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('facultet_code', models.AutoField(primary_key=True, serialize=False)),
                ('facultet_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'facultet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_sum', models.FloatField()),
                ('purpose_date', models.DateField()),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarshipPurpose',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_date', models.DateField()),
            ],
            options={
                'db_table': 'scholarship_purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scholarship_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_code', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
